# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prefrencesUi.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from ..PreferncesWidget.ColorButton import ColorButton


class UiPreferencesDialog(QtCore.QObject):
    def _setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(502, 375)
        PreferencesDialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.general_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.load_and_save_groupbox = QtWidgets.QGroupBox(self.general_tab)
        self.load_and_save_groupbox.setObjectName("load_and_save_groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.load_and_save_groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.recent_pros_num_combobox = QtWidgets.QComboBox(self.load_and_save_groupbox)
        self.recent_pros_num_combobox.setObjectName("recent_pros_num_combobox")
        self.recent_pros_num_combobox.addItems(["10", "20", "30", "40", "50"])

        self.gridLayout.addWidget(self.recent_pros_num_combobox, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.auto_save_checkbox = QtWidgets.QCheckBox(self.load_and_save_groupbox)
        self.auto_save_checkbox.setObjectName("auto_save_checkbox")
        self.gridLayout.addWidget(self.auto_save_checkbox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.load_and_save_groupbox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.interval_combobox = QtWidgets.QComboBox(self.load_and_save_groupbox)
        self.interval_combobox.setObjectName("interval_combobox")
        self.interval_combobox.addItems(["2", "3", "5", "8", "10", "15", "20"])

        self.gridLayout.addWidget(self.interval_combobox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.load_and_save_groupbox)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.load_and_save_groupbox)
        self.tabWidget.addTab(self.general_tab, "")
        self.interface_tab = QtWidgets.QWidget()
        self.interface_tab.setObjectName("interface_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.interface_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.interface_groupbox = QtWidgets.QGroupBox(self.interface_tab)
        self.interface_groupbox.setObjectName("interface_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.interface_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.language_combobox = QtWidgets.QComboBox(self.interface_groupbox)
        self.language_combobox.setObjectName("language_combobox")
        self.gridLayout_2.addWidget(self.language_combobox, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.interface_groupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.interface_groupbox)
        self.theme_groupbox = QtWidgets.QGroupBox(self.interface_tab)
        self.theme_groupbox.setObjectName("theme_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.theme_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.theme_groupbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.theme_groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.style_combobox = QtWidgets.QComboBox(self.theme_groupbox)
        self.style_combobox.setObjectName("style_combobox")
        self.gridLayout_3.addWidget(self.style_combobox, 0, 2, 1, 1)

        self.selection_color_btn = ColorButton(self.theme_groupbox)
        # self.selection_color_btn.setMinimumSize(QtCore.QSize(74, 0))
        self.selection_color_btn.setText("")
        self.selection_color_btn.setObjectName("selection_color_btn")
        self.gridLayout_3.addWidget(self.selection_color_btn, 2, 2, 1, 1)

        self.label_6 = QtWidgets.QLabel(self.theme_groupbox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)

        self.base_color_btn = ColorButton(self.theme_groupbox)
        # self.base_color_btn.setMinimumSize(QtCore.QSize(74, 0))
        self.base_color_btn.setText("")
        self.base_color_btn.setObjectName("base_color_btn")
        self.gridLayout_3.addWidget(self.base_color_btn, 1, 2, 1, 2)

        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.theme_groupbox)
        self.tabWidget.addTab(self.interface_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Dialog"))
        self.load_and_save_groupbox.setTitle(_translate("PreferencesDialog", "保存和加载"))
        self.recent_pros_num_combobox.setItemText(0, _translate("PreferencesDialog", "10"))
        self.recent_pros_num_combobox.setItemText(1, _translate("PreferencesDialog", "20"))
        self.recent_pros_num_combobox.setItemText(2, _translate("PreferencesDialog", "30"))
        self.recent_pros_num_combobox.setItemText(3, _translate("PreferencesDialog", "40"))
        self.recent_pros_num_combobox.setItemText(4, _translate("PreferencesDialog", "50"))
        self.auto_save_checkbox.setText(_translate("PreferencesDialog", "每隔"))
        self.label.setText(_translate("PreferencesDialog", "最近打开的项目列表："))
        self.interval_combobox.setItemText(0, _translate("PreferencesDialog", "2"))
        self.interval_combobox.setItemText(1, _translate("PreferencesDialog", "3"))
        self.interval_combobox.setItemText(2, _translate("PreferencesDialog", "5"))
        self.interval_combobox.setItemText(3, _translate("PreferencesDialog", "8"))
        self.interval_combobox.setItemText(4, _translate("PreferencesDialog", "10"))
        self.interval_combobox.setItemText(5, _translate("PreferencesDialog", "15"))
        self.label_2.setText(_translate("PreferencesDialog", "分钟保存正在编辑的项目"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general_tab), _translate("PreferencesDialog", "常规"))
        self.interface_groupbox.setTitle(_translate("PreferencesDialog", "界面"))
        self.label_3.setText(_translate("PreferencesDialog", "语言："))
        self.theme_groupbox.setTitle(_translate("PreferencesDialog", "主题"))
        self.label_4.setText(_translate("PreferencesDialog", "风格："))
        self.label_5.setText(_translate("PreferencesDialog", "基色："))
        self.label_6.setText(_translate("PreferencesDialog", "选中颜色："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.interface_tab), _translate("PreferencesDialog", "界面"))
